### ISSUE TITLE
Production Use

### ISSUE THREAD

**Issue by arunkjn** [gaplotech/kotlin-protobuf-bson-codec#4]
Hi, 

We wanted to persist protobuf objects to mongodb. I wanted to know if this library is good to be used in production? Are there any gotchas we should be aware of?

**Comment by gaplo917** [comment]
Hi @arunkjn ,

Persisting a **PURE** protobuf object into mongodb through KMongo is absolutely stable. I have used for few months without any issues. Also, The test cases should covered a lot of scenarios on Protobuf V3 already that you could check. 

Noted that, a mixed Kotlin `data class` or `class` with a protobuf fields are **NOT** tested yet. Personally, I don't think this "hybrid" approach is a correct way to persist protobuf as it will mixed with jackson serialization.

**Comment by arunkjn** [comment]
Hi @gaplo917, I observed that a protobuf object containing a [com.google.protobuf.Value](https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/value) type property does not serialize properly. Have you taken this into consideration? I am actually using a protobuf object in the "hybrid" approach. All the fields of the object except the one of type Value are serializing/ deserializing properly.

**Comment by arunkjn** [comment]
I see that the protobuf object used in test does not have any property of type value .
https://github.com/gaplotech/kotlin-protobuf-bson-codec/blob/master/kotlin-protobuf-bson-codec/src/test/proto/test.proto

**Comment by arunkjn** [comment]
I tried to debug further and found that the value is persisted properly with correct data types in MongoDb. But while reading, at https://github.com/gaplotech/kotlin-protobuf-bson-codec/blob/master/kotlin-protobuf-bson-codec/src/main/kotlin/io/github/gaplotech/PBBsonReader.kt#L61 the descriptor is null and so those fields are skipped.

**Comment by arunkjn** [comment]
I have modified one of the test cases to demonstrate this problem.
https://github.com/gaplotech/kotlin-protobuf-bson-codec/pull/5

The test is not passing now.

**Comment by arunkjn** [comment]
Hi @gaplo917 , I have solved this problem by changing the implementation to a simplistic approach of -

protobuf -> json -> bson
bson -> json -> protobuf

```java
  @Override
  public Message decode(BsonReader reader, DecoderContext decoderContext) {
    Message.Builder builder = null;
    try {
      builder = (Message.Builder) messageClass.getDeclaredMethod("newBuilder").invoke(messageClass);
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    } catch (InvocationTargetException e) {
      e.printStackTrace();
    } catch (NoSuchMethodException e) {
      e.printStackTrace();
    }
    StringWriter stringWriter = new StringWriter();
    JsonWriter writer = new JsonWriter(stringWriter, JsonWriterSettings.builder().build());
    writer.pipe(reader);
    try {
      JsonFormat.parser().merge(stringWriter.toString(), builder);
    } catch (InvalidProtocolBufferException e) {
      e.printStackTrace();
    }

    return builder.build();
  }

  @Override
  public void encode(BsonWriter writer, Message value, EncoderContext encoderContext) {
    String jsonString = new String();
    try {
      jsonString = JsonFormat.printer().print(value);
    } catch (InvalidProtocolBufferException e) {
      e.printStackTrace();
    }
    JsonReader reader = new JsonReader(jsonString);
    writer.pipe(reader);
  }
```

**Comment by gaplo917** [comment]
@arunkjn In this case you may probably lost some type information in your database. For example,  JSON can't represent `Protobuf: Int64` as the `JSON Number` can only represent 53 bit long exact integral value.

If you convert `Protobuf: Int64` to JSON, it will convert to `JSON: String` and then to `BSON: String`.

Expected:  `Protobuf: Int64` -> `Mongo: NumberLong()`
Actual: `Protobuf: In64` -> `JSON: String` -> `Mongo: String`

also, it needs "double" CPU power to do the serialization.

FYI, I have another project using Moshi as default JSON serializations and using exactly with this approach to save to MongoDB. You could take a look on the snippet and change some key method using protobuf JSON serialization/deserialization

```
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import org.bson.BsonReader
import org.bson.BsonWriter
import org.bson.Document
import org.bson.codecs.Codec
import org.bson.codecs.DecoderContext
import org.bson.codecs.DocumentCodec
import org.bson.codecs.EncoderContext
import org.bson.codecs.configuration.CodecProvider
import org.bson.codecs.configuration.CodecRegistry
import org.bson.json.JsonMode
import org.bson.json.JsonWriterSettings

class MoshiCodecProvider: CodecProvider {
    override fun <T : Any> get(clazz: Class<T>, registry: CodecRegistry): Codec<T>? {
        return if(clazz.isAnnotationPresent(JsonClass::class.java)){
            return MoshiCodec(clazz)
        } else {
            null
        }
    }
}

class MoshiCodec<T>(private val clazz: Class<T>) : Codec<T> {
    private val documentCodec = DocumentCodec()
    private val moshiAdapter = Moshi.Builder()
        .build()
        .adapter(clazz)
        .lenient()
        .nullSafe()

    override fun getEncoderClass(): Class<T> = clazz

    override fun decode(reader: BsonReader, decoderContext: DecoderContext): T {
        val bsonDocument = documentCodec.decode(reader, decoderContext)
        val settings = JsonWriterSettings.builder().outputMode(JsonMode.RELAXED).build()
        val json = bsonDocument.toJson(settings)
        return moshiAdapter.fromJson(json)
            ?: throw IllegalStateException("Can not prase ${clazz.name} from doc document")
    }

    override fun encode(writer: BsonWriter, value: T, encoderContext: EncoderContext) {
        val json = moshiAdapter.toJson(value)
        documentCodec.encode(writer, Document.parse(json), encoderContext)
    }
}
```

**Comment by gaplo917** [comment]
> Hi @gaplo917, I observed that a protobuf object containing a [com.google.protobuf.Value](https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/value) type property does not serialize properly. Have you taken this into consideration? I am actually using a protobuf object in the "hybrid" approach. All the fields of the object except the one of type Value are serializing/ deserializing properly.

@arunkjn Supported on 0.3.0. Thanks for you contribution
