### ISSUE TITLE
Add custom serialization for Timestamp

### ISSUE THREAD

**Issue by akionakamura** [gaplotech/kotlin-protobuf-bson-codec#6]
Wondering if it would make sense to add a custom option in `wellKnownTypeWriters` to serialize Google's common protobuf `Timestamp` either as Mongo `date` or `timestamp`. Today, it is serialized as nested `seconds` and `nanos`:

```
{
  "_id": {
    "$oid": "5feb678a63eee92a4f7082ed"
  },
  "uuidv4": "fa6ea265-ab05-494b-a511-c79d1d72e434",
  "createdTime": {
    "seconds": {
      "$numberLong": "1609262985"
    },
    "nanos": 978000000
  }
}
```

**Comment by akionakamura** [comment]
Is this still under development? I could try to contribute.

**Comment by gaplo917** [comment]
> Wondering if it would make sense to add a custom option in `wellKnownTypeWriters` to serialize Google's common protobuf `Timestamp` either as Mongo `date` or `timestamp`. Today, it is serialized as nested `seconds` and `nanos`:
> 
> 
> 
> ```
> 
> {
> 
>   "_id": {
> 
>     "$oid": "5feb678a63eee92a4f7082ed"
> 
>   },
> 
>   "uuidv4": "fa6ea265-ab05-494b-a511-c79d1d72e434",
> 
>   "createdTime": {
> 
>     "seconds": {
> 
>       "$numberLong": "1609262985"
> 
>     },
> 
>     "nanos": 978000000
> 
>   }
> 
> }
> 
> ```

As you see, there is a `nano` fields in the protobuf timestamp, both BSON Date and Timestamp cannot store this field. Thus, it is a lossy conversion.

Also, I think it would be wired when you want to make a `find` query in external MongoDB client when checking with the protobuf schema.

I am still using this codec in Kotlin and Java projects.

**Comment by akionakamura** [comment]
Yeah, we are using in production as well, thanks for the work!

Good point about the lossy conversion, I don't think this will fly as a general solution then. I'll figure something out for my case specifically. Perhaps it would be nice to add a backdoor on `PBCodec` to add custom serialization strategies.

**Comment by gaplo917** [comment]
@akionakamura Allowing to register a custom serializer can give better flexibility, but it may break the ideal usage of Protocol Buffer.

The ideal scenario is that protobuf schemas should be portable to other languages and they can also access the MongoDB data in the same way as we did in Kotlin if they could implement 100% the same way to serialize/deserialize protobuf <-> BSON.

For the timestamp, I just use `Int64 timestamp = 1` to store it.

I can also share some thoughts I haven't done yet on this project:

* Add flag to allow implicit conversion (BSON String -> PB Int32, BSON String -> PB Int64...) 
* Figure out how to nicely handle `_id` MongoDB Object ID
* Type-safely query the Protobuf based MongoDB collection

See if the aforementioned have solved in your project and welcome to contribute.

Thanks!

**Comment by akionakamura** [comment]
Thanks, @gaplo917 ! I'll be closing this issue for now then.
